### ISSUE TITLE
docker registry connectivity messed up after installing kind via kind-local

### ISSUE THREAD

**Issue by adurai81** [windmilleng/kind-local#10]
After installing kind via kind local and run through the instructions here -

```
kind-with-registry.sh
docker tag alpine localhost:5000/alpine
```

my docker connectivity to registry is messed up. I get this error -

```
docker pull radial/busyboxplus:curl
Error response from daemon: Get https://registry-1.docker.io/v2/: Not Found
```

Any ideas what is going on here ?

**Comment by adurai81** [comment]
```
docker tag alpine localhost:5000/alpine
Error response from daemon: No such image: alpine:latest
```

**Comment by adurai81** [comment]
More importantly how do I fix this ? Any help is highly appreciated.

**Comment by nicks** [comment]
Ugh, sorry to hear you're having trouble. But I can't think of any reason why this script would have broken your docker connectivity. Are you sure they're related?

Have you tried resetting Docker and seeing if that fixes the problem?

**Comment by adurai81** [comment]
I guess it may not be related (I'll close this issue)

I've re-installed docker-for-desktop. Would that reset the docker cli ?

**Comment by nicks** [comment]
yep, that should do it. Bah computers!
