### ISSUE TITLE
May be broken with KIND v0.8.0+

### ISSUE THREAD

**Issue by andymartin-sch** [windmilleng/kind-local#12]
Just a heads up, it looks like the networking refactor in [KIND 0.8.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0) may have broken the ability for the kind nodes to communicate directly to the registry over the docker interface.

Our setup has diverged a bit from the setup script here and we have the registry bind to `0.0.0.0:5000` on the host OS, so we were able to workaround the problem by having the kind node connect to the registry by going to the host OS instead.

**Comment by nicks** [comment]
ha, thanks! Ya, I saw it go out last night and was wondering if that might happen. It might be as simple as updating the script to use --net=kind
https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0
taking a look....

**Comment by nicks** [comment]
Hmmm...filed a bug upstream
https://github.com/kubernetes-sigs/kind/issues/1541

**Comment by andymartin-sch** [comment]
Thanks!

We will watch and probably switch over to the Official Solution eventually but the workaround of going through the host OS is good enough to where we aren't blocked from using KIND 0.8.0 with Tilt currently 👍

**Comment by nicks** [comment]
fixed in https://github.com/windmilleng/kind-local/pull/13
