### ISSUE TITLE
Using kaniko inside Pod container works?

### ISSUE THREAD

**Issue by see-quick** [windmilleng/kind-local#23]
I wonder if this registry works with the scenario where you have:
1.  a kind cluster with enabled local registry (set up on `localhost:5000`) 
2. and then you build a custom image on some Pod container inside that kind of cluster using f.e., the kaniko tool.

I think it will not work.

**Comment by nicks** [comment]
good question! the answer is yes!

when ctlptl sets up the local registry, it publishes a field "hostFromClusterNetwork". it's the domain name of the local registry, reachable from inside the cluster (it's always a different domain than `localhost`).

You can see an example here, which uses Ko to build images in-cluster - https://github.com/tilt-dev/ctlptl/blob/main/test/kind/e2e.sh
