### ISSUE TITLE
Not sure if this script is needed, since it's now added to upstream kind

### ISSUE THREAD

**Issue by yashbhutwala** [windmilleng/kind-local#8]
The script is now added to upstream docs: https://github.com/kubernetes-sigs/kind/blob/master/site/static/examples/kind-with-registry.sh

It's already deviating, it maybe makes sense to just point to the upstream one 😄

**Comment by nicks** [comment]
did you see this comment?

> This repo modifies the Kind team's script to annotate the nodes with information about the local registry, so that Tilt can find it.

from: https://github.com/windmilleng/kind-local/blob/master/README.md

yes, we expect this solution to evolve over time

**Comment by nicks** [comment]
And for what it's worth - yes, we've been talking with the Kind team on this feature. See where we originally requested it here: https://github.com/kubernetes-sigs/kind/issues/602

I do hope this script eventually goes away, but it's still needed for the `kubectl annotate node` calls

in the meantime, let us know if you have any trouble getting Kind + Tilt + local registry playing nice together.
